Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "ubuntu-bionic"
  config.vm.define "ubuntu18"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "sf_practice"
    vb.memory = "2048"
    vb.cpus = "2"
  end

  config.vm.provision "shell", inline: <<-SHELL
  sudo apt-get update && sudo apt-get install -y python3 python3-pip python3-dev libpq-dev
  pip3 install psycopg2-binary Django
  SHELL
  config.vm.provision "file", source: "./empty.file", destination: "~/empty.file"
end